apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crossplane
spec:
  interval: 6h
  url: https://charts.crossplane.io/preview
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
spec:
  interval: 15m
  chart:
    spec:
      chart: crossplane
      version: "2.0.0-preview.1"
      sourceRef:
        kind: HelmRepository
        name: crossplane
  releaseName: crossplane
  targetNamespace: crossplane-system
